DROP FUNCTION IF EXISTS fib;

CREATE FUNCTION fib (num INT)
RETURNS INT DETERMINISTIC
BEGIN
	DECLARE i INT DEFAULT 0;
	DECLARE fib INT DEFAULT 0;
	WHILE i <= num DO		
		SET fib = fib + i;
		SET i = i + 1;
	END WHILE;
	RETURN fib;
END